Repository keptn/keptn, pull requests merged in 2022-06, with the labels that each got.

#7940 fix: Ensure all MongoDB cursors are being closed
  mongodb-datastore/db/mongodb_event_repo.go
  shipyard-controller/db/common.go
  shipyard-controller/db/mongodb.go
  shipyard-controller/db/mongodb_event_repo.go
  shipyard-controller/db/mongodb_eventqueue_repo.go
  shipyard-controller/db/mongodb_log_repo.go
  shipyard-controller/db/mongodb_state_repo.go
  shipyard-controller/db/mongodb_task_sequence_repo.go
  shipyard-controller/db/mongodb_uniform_repo.go
  statistics-service/db/migrator.go
  statistics-service/db/statistics_mongodb_repo.go
Labels: CI:trigger-build-everything

#7945 fix: Ensure all MongoDB cursors are being closed
  mongodb-datastore/db/mongodb_event_repo.go
  shipyard-controller/db/common.go
  shipyard-controller/db/mongodb.go
  shipyard-controller/db/mongodb_event_repo.go
  shipyard-controller/db/mongodb_eventqueue_repo.go
  shipyard-controller/db/mongodb_log_repo.go
  shipyard-controller/db/mongodb_state_repo.go
  shipyard-controller/db/mongodb_uniform_repo.go
  statistics-service/db/migrator.go
  statistics-service/db/statistics_mongodb_repo.go
Labels: CI:trigger-build-everything

#7946 fix: Ensure all MongoDB cursors are being closed
  mongodb-datastore/db/mongodb_event_repo.go
  shipyard-controller/db/common.go
  shipyard-controller/db/mongodb.go
  shipyard-controller/db/mongodb_event_repo.go
  shipyard-controller/db/mongodb_eventqueue_repo.go
  shipyard-controller/db/mongodb_log_repo.go
  shipyard-controller/db/mongodb_state_repo.go
  shipyard-controller/db/mongodb_uniform_repo.go
  statistics-service/db/migrator.go
  statistics-service/db/statistics_mongodb_repo.go
Labels: CI:trigger-build-everything

#7860 test: Added envconfig for setting up zero downtime test parameters
  docs/developer/zero_downtime_tests.md
  test/zero-downtime/API_test.go
  test/zero-downtime/assets/test-values.yml
  test/zero-downtime/go.mod
  test/zero-downtime/go.sum
  test/zero-downtime/sequences_test.go
  test/zero-downtime/testsuite_zerodowntime_test.go
  test/zero-downtime/webhook_test.go
Labels: area:core, CI:trigger-build-everything

#8061 docs(cli): Improve CLI Documentation
  CONTRIBUTORS.md
  cli/cmd/install.go
  cli/cmd/root.go
  cli/cmd/send_event_approvalFinished.go
Labels: doc

#8123 fix(resource-service): Always delete local project directory when project creation fails
  resource-service/handler/project_manager.go
  resource-service/handler/project_manager_test.go
Labels: CI:trigger-build-everything

#8178 build(deps): Update go-utils
  cli/go.mod
  cli/go.sum
  configuration-service/go.mod
  configuration-service/go.sum
  distributor/go.mod
  distributor/go.sum
  helm-service/go.mod
  helm-service/go.sum
  jmeter-service/go.mod
  jmeter-service/go.sum
  remediation-service/go.mod
  remediation-service/go.sum
  resource-service/go.mod
  resource-service/go.sum
  secret-service/go.mod
  secret-service/go.sum
  shipyard-controller/go.mod
  shipyard-controller/go.sum
  shipyard-controller/handler/uniformintegrationhandler_test.go
  statistics-service/go.mod
  statistics-service/go.sum
  test/go-tests/go.mod
  test/go-tests/go.sum
  test/zero-downtime/go.mod
  test/zero-downtime/go.sum
  webhook-service/go.mod
  webhook-service/go.sum
Labels: CI:trigger-build-everything

#8040 fix(resource-service): Remove token enforcement
  resource-service/common/credentials_test.go
  resource-service/common_models/git.go
  resource-service/common_models/git_test.go
Labels: CI:trigger-build-everything
