Repository keptn/keptn, pull requests merged in 2022-12, with the labels that each got.

#9206 fix(lighthouse-service): fail with descriptive error message when SLO criteria and target cannot be parsed
  lighthouse-service/event_handler/evaluate_sli_handler.go
  lighthouse-service/event_handler/evaluate_sli_handler_test.go
  lighthouse-service/main_test.go
Labels: CI:trigger-build-everything

#9288 feat(installer): Use scarf registry as default
  installer/manifests/keptn/README.md
  installer/manifests/keptn/values.yaml
Labels: CI:trigger-build-everything, on hold

#9278 build(deps): Update go-utils dependency
  api/go.mod
  api/go.sum
  approval-service/go.mod
  approval-service/go.sum
  cli/go.mod
  cli/go.sum
  distributor/go.mod
  distributor/go.sum
  installer/manifests/keptn/templates/_helpers.tpl
  lighthouse-service/go.mod
  lighthouse-service/go.sum
  mongodb-datastore/go.mod
  mongodb-datastore/go.sum
  remediation-service/go.mod
  remediation-service/go.sum
  resource-service/go.mod
  resource-service/go.sum
  resource-service/handler/common.go
  secret-service/go.mod
  secret-service/go.sum
  shipyard-controller/go.mod
  shipyard-controller/go.sum
  statistics-service/go.mod
  statistics-service/go.sum
  test/go-tests/go.mod
  test/go-tests/go.sum
  test/zero-downtime/go.mod
  test/zero-downtime/go.sum
  webhook-service/go.mod
  webhook-service/go.sum
Labels: CI:trigger-build-everything

#9303 test: add extra runs and logs
  .github/workflows/integration_tests.yml
  resource-service/common/credentials.go
  resource-service/common/git.go
  test/go-tests/k8s_utils.go
  test/go-tests/test_backuprestore.go
  test/go-tests/test_custom_git_branch_name.go
  test/go-tests/test_deliveryassistant.go
  test/go-tests/test_gitcommitid.go
  test/go-tests/test_importer.go
  test/go-tests/test_provisioningURL.go
  test/go-tests/test_proxyauth.go
  test/go-tests/test_qualitygate.go
  test/go-tests/test_resourceservice.go
  test/go-tests/test_secrets.go
  test/go-tests/test_sequencequeue.go
  test/go-tests/test_sshpublickeyauth.go
Labels: CI:trigger-build-everything

#9044 chore: Move to full release
  .versionrc.json
  CHANGELOG.md
  release-please-config.json
Labels: on hold

#9319 ci: Fix generic version when no upcoming version can be used
  .github/workflows/CI.yml
Labels: CI:trigger-build-everything

#9335 feat(bridge): Read secrets from volume mount instead from env var
  bridge/README.md
  bridge/server/interfaces/configuration.ts
  bridge/server/test/bridge-info.spec.ts
  bridge/server/test/oauth.spec.ts
  bridge/server/user/secrets.spec.ts
  bridge/server/user/secrets.ts
  bridge/server/utils/configuration.spec.ts
  bridge/server/utils/configuration.ts
  installer/manifests/keptn/templates/core.yaml
Labels: CI:trigger-build-everything

#9350 build(deps): rebuild helm charts
  .github/workflows/integration_tests.yml
Labels: CI:trigger-build-everything

#9357 build(deps): rebuild helm charts
  .github/workflows/integration_tests.yml
  installer/airgapped/pull_and_retag_images.sh
Labels: CI:trigger-build-everything
