Repository keptn/keptn, pull requests merged in 2022-03, with the labels that each got.

#7046 fix(shipyard-controller): Do not reset subscriptions when updating distributor/integration version
  shipyard-controller/db/mock/uniformrepo_mock.go
  shipyard-controller/db/mongodb_uniform_repo.go
  shipyard-controller/db/mongodb_uniform_repo_test.go
  shipyard-controller/db/repos.go
  shipyard-controller/handler/uniformintegrationhandler.go
  shipyard-controller/handler/uniformintegrationhandler_test.go
  test/go-tests/test_uniform.go
Labels: CI:trigger-build-everything

#6977 feat(shipyard-controller): Introduce new data model
  installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml
  shipyard-controller/common/utils.go
  shipyard-controller/common/utils_test.go
  shipyard-controller/db/mock/sequenceexecution_mock.go
  shipyard-controller/db/mongodb_eventqueue_repo.go
  shipyard-controller/db/mongodb_project_mv_repo.go
  shipyard-controller/db/mongodb_sequence_execution_repo.go
  shipyard-controller/db/mongodb_sequence_execution_repo_test.go
  shipyard-controller/db/mongodb_task_sequence_repo.go
  shipyard-controller/db/mongodb_task_sequence_repo_test.go
  shipyard-controller/db/repos.go
  shipyard-controller/handler/eventdispatcher.go
  shipyard-controller/handler/eventdispatcher_test.go
  shipyard-controller/handler/projectmanager.go
  shipyard-controller/handler/projectmanager_test.go
  shipyard-controller/handler/sequencedispatcher.go
  shipyard-controller/handler/sequencedispatcher_test.go
  shipyard-controller/handler/shipyardcontroller.go
  shipyard-controller/handler/shipyardcontroller_component_test.go
  shipyard-controller/handler/shipyardcontroller_test.go
  shipyard-controller/handler/shipyardcontroller_utils.go
  shipyard-controller/handler/shipyardcontroller_utils_test.go
  shipyard-controller/main.go
  shipyard-controller/models/eventscope.go
  shipyard-controller/models/eventscope_test.go
  shipyard-controller/models/sequence_execution.go
  shipyard-controller/models/sequence_execution_test.go
  shipyard-controller/models/state.go
  shipyard-controller/nats/connection.go
  shipyard-controller/nats/connection_test.go
  shipyard-controller/nats/publisher.go
  test/go-tests/test_selfhealing.go
  test/go-tests/test_sequencecontrol.go
  test/go-tests/test_sequencestate.go
  test/go-tests/test_sequencetrigger.go
  test/go-tests/test_uniform.go
  test/go-tests/test_zerodowntime.go
Labels: CI:trigger-build-everything

#7059 fix(shipyard-controller): Do not reset subscriptions when updating distributor/integration version
  shipyard-controller/db/mock/uniformrepo_mock.go
  shipyard-controller/db/mongodb_uniform_repo.go
  shipyard-controller/db/mongodb_uniform_repo_test.go
  shipyard-controller/db/repos.go
  shipyard-controller/handler/uniformintegrationhandler.go
  shipyard-controller/handler/uniformintegrationhandler_test.go
  test/go-tests/test_uniform.go
Labels: CI:trigger-build-everything

#7058 fix(shipyard-controller): Do not reset subscriptions when updating distributor/integration version
  shipyard-controller/db/mock/uniformrepo_mock.go
  shipyard-controller/db/mongodb_uniform_repo.go
  shipyard-controller/db/mongodb_uniform_repo_test.go
  shipyard-controller/db/repos.go
  shipyard-controller/handler/uniformintegrationhandler.go
  shipyard-controller/handler/uniformintegrationhandler_test.go
  test/go-tests/test_uniform.go
Labels: CI:trigger-build-everything

#7080 fix: Normalize error messages
  secret-service/pkg/handler/common.go
  secret-service/pkg/handler/scopehandler.go
  secret-service/pkg/handler/secrethandler.go
  shipyard-controller/db/mongodb_event_repo.go
  shipyard-controller/db/mongodb_eventqueue_repo.go
  shipyard-controller/deploy/service.yaml
  shipyard-controller/handler/common.go
  shipyard-controller/handler/common_test.go
  shipyard-controller/handler/error.go
  shipyard-controller/handler/evaluationhandler.go
  shipyard-controller/handler/evaluationhandler_test.go
  shipyard-controller/handler/eventhandler.go
  shipyard-controller/handler/loghandler.go
  shipyard-controller/handler/projecthandler.go
  shipyard-controller/handler/sequencedispatcher.go
  shipyard-controller/handler/sequencehooks/sequencestate.go
  shipyard-controller/handler/sequencewatcher.go
  shipyard-controller/handler/servicehandler.go
  shipyard-controller/handler/shipyardcontroller.go
  shipyard-controller/handler/stagehandler.go
  shipyard-controller/handler/statehandler.go
  shipyard-controller/handler/uniformintegrationhandler.go
Labels: CI:trigger-build-everything

#7109 fix(distributor): Fixed reconnection issue of (re)used ce clients
  distributor/pkg/forwarder/forwarder.go
  distributor/pkg/forwarder/forwarder_test.go
  distributor/pkg/receiver/receiver_test.go
Labels: CI:trigger-build-everything

#7114 fix(shipyard-controller): Make sure sequence queue is free again after aborting a sequence
  .github/workflows/integration_tests.yml
  shipyard-controller/db/mock/tasksequencerepo_mock.go
  shipyard-controller/db/mongodb_task_sequence_repo.go
  shipyard-controller/db/mongodb_task_sequence_repo_test.go
  shipyard-controller/db/repos.go
  shipyard-controller/handler/eventdispatcher.go
  shipyard-controller/handler/sequencehooks/fake/sequenceaborted.go
  shipyard-controller/handler/sequencehooks/hooks.go
  shipyard-controller/handler/sequencehooks/sequencestate.go
  shipyard-controller/handler/shipyardcontroller.go
  shipyard-controller/handler/shipyardcontroller_component_test.go
  shipyard-controller/handler/shipyardcontroller_hooks.go
  test/go-tests/test_sequencecontrol.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
Labels: CI:trigger-build-everything

#7144 fix(webhook-service): Fix retrieval of webhook config
  test/go-tests/test_webhook.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
  webhook-service/handler/fake/resource_handler_mock.go
  webhook-service/handler/handler.go
  webhook-service/handler/handler_test.go
  webhook-service/handler/interfaces.go
Labels: CI:trigger-build-everything

#7121 fix(configuration-service): Return 404 when token is invalid
  configuration-service/handlers/project.go
  shipyard-controller/common/configurationstore.go
  shipyard-controller/common/configurationstore_test.go
Labels: CI:trigger-build-everything

#7126 fix(shipyard-controller): Make sure sequence queue is free again after aborting a sequence
  .github/workflows/integration_tests.yml
  shipyard-controller/db/mock/tasksequencerepo_mock.go
  shipyard-controller/db/mongodb_task_sequence_repo.go
  shipyard-controller/db/mongodb_task_sequence_repo_test.go
  shipyard-controller/db/repos.go
  shipyard-controller/handler/shipyardcontroller.go
  shipyard-controller/handler/shipyardcontroller_component_test.go
  test/go-tests/test_sequencecontrol.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
Labels: CI:trigger-build-everything

#7110 docs: Reference the code of conduct in the .github repository
  CODE_OF_CONDUCT.md
Labels: type:chore

#7148 test: Enhance quality-gates testing
  cli/cmd/trigger_evaluation_test.go
  lighthouse-service/event_handler/common.go
  lighthouse-service/event_handler/common_test.go
  lighthouse-service/event_handler/start_evaluation_handler_test.go
  shipyard-controller/handler/evaluationhandler.go
  shipyard-controller/handler/evaluationhandler_test.go
  shipyard-controller/handler/evaluationmanager_test.go
  shipyard-controller/models/evaluation.go
  test/go-tests/test_qualitygate.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
Labels: CI:trigger-build-everything

#7211 fix(lighthouse-service): Fail sequence when evaluation is aborted/errored
  lighthouse-service/deploy/service.yaml
  lighthouse-service/event_handler/evaluate_sli_handler.go
  test/go-tests/test_qualitygate.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
Labels: CI:trigger-build-everything

#7175 fix(shipyard-controller): Abort multi-stage sequences
  shipyard-controller/handler/shipyardcontroller.go
  test/go-tests/test_sequencecontrol.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
Labels: CI:trigger-build-everything

#7223 test: Add safe-to-evict annotation to enable frictionless autoscaling
  test/assets/podtato-head/helm-charts/helloservice.tgz
  test/assets/podtato-head/helm-charts/helloservice/Chart.yaml
  test/assets/podtato-head/helm-charts/helloservice/templates/deployment.yaml
  test/assets/podtato-head/helm-charts/helloservice/templates/service.yaml
  test/assets/podtato-head/helm-charts/helloservice/values.yaml
  test/go-tests/go.mod
  test/go-tests/go.sum
  test/go-tests/test_backuprestore.go
  test/go-tests/test_continuous_delivery.go
  test/go-tests/test_graceful_shutdown.go
  test/go-tests/test_proxyauth.go
  test/go-tests/test_sshpublickeyauth.go
Labels: CI:trigger-build-everything

#7237 fix(shipyard-controller): Consider parallel stages when trying to set overall sequence state to finished
  shipyard-controller/handler/sequencehooks/sequencestate.go
  shipyard-controller/handler/sequencehooks/sequencestate_test.go
  test/go-tests/test_sequencestate.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
Labels: CI:trigger-build-everything

#7215 fix(resource-service): fix nats subscription and added retry logic
  .github/workflows/integration_tests.yml
  resource-service/common/fake/git_mock.go
  resource-service/common/git.go
  resource-service/go.mod
  resource-service/handler/nats/eventhandler.go
  resource-service/handler/nats/eventhandler_test.go
  resource-service/handler/project_manager_test.go
  resource-service/handler/resource_manager.go
  resource-service/handler/resource_manager_test.go
  resource-service/handler/service_manager.go
  resource-service/handler/service_manager_test.go
  resource-service/main.go
  resource-service/nats/connection.go
  resource-service/nats/connection_test.go
  resource-service/nats/mock/keptn_nats_handler_mock.go
  resource-service/nats/publisher.go
  resource-service/nats/pullsubscription.go
  resource-service/pkg/nats/subscriber/sub.go
  resource-service/pkg/nats/subscriber/sub_test.go
  test/go-tests/test_backuprestore.go
  test/go-tests/test_proxyauth.go
  test/go-tests/test_sshpublickeyauth.go
Labels: CI:trigger-build-everything

#7269 feat(api): Added automaticProvisioning helm value to api-service
  api/deploy/service.yaml
  api/handlers/metadata.go
  api/handlers/metadata_test.go
  api/models/metadata.go
  api/restapi/embedded_spec.go
  api/swagger.yaml
  installer/manifests/keptn/charts/control-plane/templates/api-service.yaml
  installer/manifests/keptn/charts/control-plane/values.yaml
Labels: CI:trigger-build-everything

#7250 fix(shipyard-controller): Consider parallel stages when trying to set overall sequence state to finished
  shipyard-controller/handler/sequencehooks/sequencestate.go
  shipyard-controller/handler/sequencehooks/sequencestate_test.go
  test/go-tests/test_sequencestate.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
Labels: CI:trigger-build-everything

#7145 chore: Replace the Security guidelines by the hyperlink
  SECURITY.md
Labels: doc, area:security, security

#7181 chore: Add Slack issue link
  .github/config.yml
Labels: type:chore

#7155 docs: Stop-gap info about filtering by stage, project,service
  distributor/README.md
  helm-service/chart/values.yaml
Labels: doc

#7191 fix(webhook-service): enhance denylist of disallowed urls
  webhook-service/lib/curl_executor.go
  webhook-service/lib/curl_executor_test.go
  webhook-service/main.go
Labels: CI:trigger-build-everything

#7314 ci: Pass datetime and git sha to docker build in release pipelines
  .github/workflows/CI.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
Labels: automation

#7276 feat(shipyard-controller): Introduce automatic provisioning of gitRemoteURI
  .github/workflows/integration_tests.yml
  distributor/pkg/clientget/client.go
  installer/manifests/keptn/charts/control-plane/templates/shipyard-controller.yaml
  resource-service/deploy/service.yaml
  shipyard-controller/config/envconfig.go
  shipyard-controller/deploy/service.yaml
  shipyard-controller/docs/swagger.yaml
  shipyard-controller/handler/error.go
  shipyard-controller/handler/fake/repository_provisioner_mock.go
  shipyard-controller/handler/projecthandler.go
  shipyard-controller/handler/projecthandler_test.go
  shipyard-controller/handler/projectmanager.go
  shipyard-controller/handler/repository_provisioner.go
  shipyard-controller/handler/repository_provisioner_test.go
  shipyard-controller/main.go
  shipyard-controller/models/provision.go
  test/go-tests/test_provisioningURL.go
  test/go-tests/test_proxyauth.go
  test/go-tests/test_utils.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
Labels: CI:trigger-build-everything
