Repository keptn/keptn, pull requests merged in 2022-01, with the labels that each got.

#6497 ci: Fix codecov reporting and monorepo setup
  .github/workflows/CI.yml
  codecov.yml
Labels: CI:trigger-build-everything

#6486 fix: Added delay and logging to graceful shutdown (#6485)
  test/go-tests/test_graceful_shutdown.go
Labels: CI:trigger-build-everything

#6515 test: Catch Out of Memory Errors during integration tests
  test/go-tests/go.mod
  test/go-tests/go.sum
  test/go-tests/init_test.go
  test/go-tests/k8s_utils.go
  test/go-tests/kubectl.go
Labels: CI:trigger-build-everything

#6326 perf(shipyard-controller): Remove DB connection locking
  shipyard-controller/db/mongodb_connection.go
Labels: CI:trigger-build-everything

#6522 chore: Promote @oleg-nenashev to maintainers
  MAINTAINERS
Labels: type:chore

#6530 feat(resource-service): Complete implementation of Service
  installer/manifests/keptn/charts/control-plane/templates/core.yaml
  installer/manifests/keptn/charts/control-plane/values.yaml
  resource-service/.gitignore
  resource-service/common/credentials.go
  resource-service/common/credentials_test.go
  resource-service/common/files.go
  resource-service/common/git.go
  resource-service/common/gitsuite_test.go
  resource-service/common_models/git.go
  resource-service/common_models/git_test.go
  resource-service/controller/healthcontroller.go
  resource-service/controller/stage_controller.go
  resource-service/errors/errors.go
  resource-service/handler/common.go
  resource-service/handler/gracefulshutdownmiddleware.go
  resource-service/handler/healthhandler.go
  resource-service/handler/project_manager.go
  resource-service/handler/project_manager_test.go
  resource-service/handler/project_resource_handler.go
  resource-service/handler/resource_manager.go
  resource-service/handler/resource_manager_test.go
  resource-service/handler/service_resource_handler.go
  resource-service/handler/stage_resource_handler.go
  resource-service/main.go
  test/go-tests/test_resourceservice.go
Labels: CI:trigger-build-everything

#6457 fix(configuration-service): Make check for helm chart archives more strict (#6447)
  configuration-service/handlers/service_resource.go
  configuration-service/handlers/service_resource_test.go
Labels: CI:trigger-build-everything

#6549 feat(cli): SSO integration
  cli/cmd/add_resource.go
  cli/cmd/add_resource_test.go
  cli/cmd/auth.go
  cli/cmd/authenticator.go
  cli/cmd/configure_monitoring.go
  cli/cmd/configure_monitoring_test.go
  cli/cmd/create_project.go
  cli/cmd/create_project_test.go
  cli/cmd/create_service.go
  cli/cmd/create_service_test.go
  cli/cmd/delete_project.go
  cli/cmd/delete_project_test.go
  cli/cmd/delete_service.go
  cli/cmd/generate_docs_test.go
  cli/cmd/generate_support_archive.go
  cli/cmd/generate_support_archive_test.go
  cli/cmd/get_event.go
  cli/cmd/get_event_approvalTriggered.go
  cli/cmd/get_event_approvalTriggered_test.go
  cli/cmd/get_event_evaluationFinished.go
  cli/cmd/get_event_evaluationFinished_test.go
  cli/cmd/get_event_test.go
  cli/cmd/get_projects.go
  cli/cmd/get_projects_test.go
  cli/cmd/get_services.go
  cli/cmd/get_services_test.go
  cli/cmd/get_stages.go
  cli/cmd/get_stages_test.go
  cli/cmd/main_test.go
  cli/cmd/root_test.go
  cli/cmd/secret.go
  cli/cmd/send_event.go
  cli/cmd/send_event_approvalFinished.go
  cli/cmd/send_event_approvalFinished_test.go
  cli/cmd/send_event_evaluationStart_test.go
  cli/cmd/send_event_newArtifact_test.go
  cli/cmd/send_event_test.go
  cli/cmd/sequencecontrol.go
  cli/cmd/trigger_delivery.go
  cli/cmd/trigger_delivery_test.go
  cli/cmd/trigger_evaluation.go
  cli/cmd/update_project.go
  cli/cmd/update_project_test.go
  cli/cmd/upgrade.go
  cli/cmd/upgrade_test.go
  cli/cmd/version.go
  cli/cmd/version_test.go
  cli/go.mod
  cli/go.sum
  cli/internal/api.go
  cli/internal/auth/browser.go
  cli/internal/auth/discovery.go
  cli/internal/auth/discovery_test.go
  cli/internal/auth/mocks.go
  cli/internal/auth/oauth.go
  cli/internal/auth/oauth_test.go
  cli/internal/auth/pkce.go
  cli/internal/auth/redirect.go
  cli/internal/auth/refresh.go
  cli/internal/auth/store.go
Labels: CI:trigger-build-everything

#6578 fix: Support Openshift 3.11
  installer/manifests/keptn/charts/control-plane/templates/ingress.yaml
Labels: CI:trigger-build-everything

#6597 feat(shipyard-controller): Propagate git commit ID passed in sequence.triggered events (#6348)
  api/go.mod
  api/go.sum
  api/handlers/event.go
  api/models/keptn_context_extended_c_e.go
  api/restapi/embedded_spec.go
  api/restapi/operations/event/post_event.go
  api/restapi/operations/event/post_event_parameters.go
  api/utils/event.go
  distributor/go.mod
  distributor/go.sum
  mongodb-datastore/go.mod
  mongodb-datastore/go.sum
  mongodb-datastore/models/keptn_context_extended_c_e.go
  mongodb-datastore/restapi/embedded_spec.go
  shipyard-controller/common/configurationstore.go
  shipyard-controller/common/fake/configurationstore_mock.go
  shipyard-controller/go.mod
  shipyard-controller/go.sum
  shipyard-controller/handler/fake/shipyardretriever_mock.go
  shipyard-controller/handler/shipyardcontroller.go
  shipyard-controller/handler/shipyardcontroller_component_test.go
  shipyard-controller/handler/shipyardretriever.go
  shipyard-controller/handler/shipyardretriever_test.go
  shipyard-controller/models/event.go
  shipyard-controller/models/eventscope.go
  test/go-tests/go.mod
  test/go-tests/go.sum
  test/go-tests/test_sequencestate.go
Labels: CI:trigger-build-everything

#6629 fix(installer): Fixed helm/jmeter service helm values schema
  helm-service/chart/values.schema.json
  jmeter-service/chart/values.schema.json
Labels: CI:trigger-build-everything

#6559 feat: Release helm charts on GitHub pages
  .github/workflows/CI.yml
  .github/workflows/create_release_branch.yml
  .github/workflows/dependencies-and-licenses.yml
  .github/workflows/pre-release.yml
  .github/workflows/release.yml
  README.md
  cli/cmd/install.go
  cli/cmd/install_test.go
  cli/cmd/install_upgrade_params.go
  cli/cmd/upgrade.go
  cli/cmd/upgrade_test.go
  docs/install_master.md
  gh-actions-scripts/upload_helm_chart_to_google_cloud.sh
  releasenotes/releasenotes_V0.8.5.md
  releasenotes/releasenotes_V0.8.6.md
  test/assertEquals.sh
  test/test_install_gke.sh
  test/test_install_kubernetes_full.sh
  test/test_install_minishift_quality_gates.sh
  test/test_install_on_kubernetes.sh
  test/test_keptn_performance.sh
  test/test_keptn_uninstall.sh
  test/utils/check_bridge_availability.sh
  test/utils/download_and_install_keptn_cli.sh
  test/utils/gke_authenticate_at_keptn.sh
  test/utils/microk8s_create_cluster.sh
  test/utils/trigger_delivery_sockshop.sh
Labels: CI:trigger-build-everything

#6641 fix: Adapt http status code for not found upstream repositories
  configuration-service/common/common.go
  configuration-service/common/git.go
  configuration-service/handlers/project.go
  resource-service/handler/common.go
  resource-service/handler/project_handler_test.go
  resource-service/handler/service_handler_test.go
  shipyard-controller/common/configurationstore.go
  shipyard-controller/handler/error.go
  shipyard-controller/handler/projecthandler.go
  shipyard-controller/handler/projecthandler_test.go
  shipyard-controller/handler/projectmanager.go
Labels: CI:trigger-build-everything

#6654 fix(configuration-service): Ensure that git user and email are set before committing (#6645)
  configuration-service/common/git.go
  configuration-service/common/git_test.go
  configuration-service/handlers/project.go
Labels: CI:trigger-build-everything

#6603 feat: Introduce 'waiting' status to sequences
  shipyard-controller/common/event.go
  shipyard-controller/common/utils.go
  shipyard-controller/common/utils_test.go
  shipyard-controller/go.mod
  shipyard-controller/go.sum
  shipyard-controller/handler/error.go
  shipyard-controller/handler/eventdispatcher.go
  shipyard-controller/handler/eventdispatcher_test.go
  shipyard-controller/handler/sequencedispatcher.go
  shipyard-controller/handler/sequencedispatcher_test.go
  shipyard-controller/handler/sequencehooks/fake/sequencewaiting.go
  shipyard-controller/handler/sequencehooks/hooks.go
  shipyard-controller/handler/sequencehooks/sequencestate.go
  shipyard-controller/handler/sequencehooks/sequencestate_test.go
  shipyard-controller/handler/sequencewatcher.go
  shipyard-controller/handler/shipyardcontroller.go
  shipyard-controller/handler/shipyardcontroller_hooks.go
  shipyard-controller/main.go
  shipyard-controller/models/state.go
  test/go-tests/go.sum
  test/go-tests/test_sequencecontrol.go
  test/go-tests/test_sequencequeue.go
Labels: CI:trigger-build-everything

#6020 feat: Update pod config to be more strict w.r.t. security
  installer/manifests/keptn/charts/control-plane/templates/api-gateway-nginx.yaml
  installer/manifests/keptn/charts/control-plane/templates/continuous-operations.yaml
  installer/manifests/keptn/charts/control-plane/templates/core.yaml
  installer/manifests/keptn/charts/control-plane/templates/mongodb-datastore.yaml
  installer/manifests/keptn/charts/control-plane/templates/quality-gates.yaml
  installer/manifests/keptn/charts/control-plane/templates/rbac.yaml
Labels: CI:trigger-build-everything

#6658 fix(installer): Set distributor version in helm chart (#6652)
  helm-service/chart/templates/deployment.yaml
  installer/manifests/keptn/charts/control-plane/templates/_helpers.tpl
  jmeter-service/chart/templates/deployment.yaml
  test/go-tests/test_uniform.go
Labels: CI:trigger-build-everything

#6670 ci: Fix intergation tests taking master artifacts from bot commits
  .github/workflows/integration_tests.yml
Labels: automation

#6664 feat(webhook-service): Allow disabling .started events (#6524)
  .github/workflows/integration_tests.yml
  test/go-tests/test_webhook.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
  test/go-tests/testsuite_openshift_test.go
  webhook-service/README.md
  webhook-service/handler/handler.go
  webhook-service/handler/handler_test.go
  webhook-service/lib/webhook_config.go
  webhook-service/lib/webhook_config_test.go
Labels: CI:trigger-build-everything

#6671 docs: Add structure for developer documentation
  CONTRIBUTING.md
  docs/README.md
  docs/developer/README.md
  docs/developer/assets/gh_action_Integration_tests.png
  docs/developer/assets/gh_action_ci_run.png
  docs/developer/assets/gh_action_create_release_branch.png
  docs/developer/assets/git_branch_workflow.png
  docs/developer/assets/goland_cloud_code_select.png
  docs/developer/assets/goland_remote_debugger.png
  docs/developer/assets/goland_run_configurations.png
  docs/developer/bridge.md
  docs/developer/core.md
  docs/developer/debugging.md
  docs/developer/fork.md
  docs/developer/how_to_release_using_gh_actions.md
  docs/developer/install_master.md
  docs/developer/integration_tests.md
  docs/developer/pipelines.md
Labels: doc

#6675 feat(cli): Allow to skip sending the API token when using an SSO integration
  cli/cmd/add_resource.go
  cli/cmd/add_resource_test.go
  cli/cmd/auth.go
  cli/cmd/authenticator.go
  cli/cmd/check_endpoint_status.go
  cli/cmd/check_endpoint_status_test.go
  cli/cmd/configure_monitoring.go
  cli/cmd/configure_monitoring_test.go
  cli/cmd/create_project.go
  cli/cmd/create_project_test.go
  cli/cmd/create_service.go
  cli/cmd/create_service_test.go
  cli/cmd/delete_project.go
  cli/cmd/delete_project_test.go
  cli/cmd/get_event.go
  cli/cmd/get_event_approvalTriggered.go
  cli/cmd/get_event_evaluationFinished.go
  cli/cmd/get_event_evaluationFinished_test.go
  cli/cmd/get_projects.go
  cli/cmd/get_projects_test.go
  cli/cmd/get_services.go
  cli/cmd/get_services_test.go
  cli/cmd/get_stages.go
  cli/cmd/get_stages_test.go
  cli/cmd/helpers.go
  cli/cmd/main_test.go
  cli/cmd/secret.go
  cli/cmd/send_event.go
  cli/cmd/send_event_approvalFinished.go
  cli/cmd/send_event_evaluationStart_test.go
  cli/cmd/send_event_newArtifact_test.go
  cli/cmd/send_event_test.go
  cli/cmd/sequencecontrol.go
  cli/cmd/trigger_delivery.go
  cli/cmd/trigger_delivery_test.go
  cli/cmd/trigger_evaluation.go
  cli/cmd/trigger_evaluation_test.go
  cli/cmd/update_project.go
  cli/cmd/update_project_test.go
  cli/cmd/upgrade_test.go
  cli/cmd/version.go
  cli/cmd/version_test.go
  cli/internal/api.go
  cli/internal/auth/oauth.go
  cli/pkg/credentialmanager/handler.go
  cli/pkg/credentialmanager/handler_linux.go
Labels: CI:trigger-build-everything

#6612 feat(mongodb-datastore): Use simple join query instead of uncorrelated sub-query
  mongodb-datastore/common/common.go
  mongodb-datastore/common/common_test.go
  mongodb-datastore/db/mongodb_event_repo.go
  mongodb-datastore/db/mongodb_event_repo_test.go
  test/go-tests/test_qg_bw_compatibility.go
  test/go-tests/testsuite_gke_test.go
  test/go-tests/testsuite_k3s_test.go
Labels: CI:trigger-build-everything
